### ISSUE TITLE
FIX: Particles for food and water in bathing + feeding task

### ISSUE THREAD

**Issue by TheMagicalFishTaco** [BlizzardBunny/RAWRS#20]
can just use UI element / images for water. actual particle system probably isn't going to work
or force the particles to position themselves in front of camera, but this will depend on transparency of UI elements

^ what Sir Diy said. If you remember one of the homework for GDEV 41, you can basically do the same but replace circles with the confetti sprites

**Comment by BlizzardBunny** [comment]
"Try out Sir Jayzon's sample project to see if it solves particle issue #30"

> The gist is as follows:
> - Create a RenderTexture in the Assets folder
> - Create a Particle system assigned to a different custom layer ("UIParticles" layer in the sample project)
>   - Create a new material for the particle system, set the shader to "Unlit/Transparent"; You can then set your desired texture
>   - Under "Renderer", set the material to the material above
> - A second camera is set up which renders only the particle system
>   - Clear flags set to Solid Color, (0, 0, 0, 0)
>   - Culling mask set to the "UIParticles" layer (i.e., only renders game objects that are assigned to the UIParticles layer)
>   - Target texture set to the render texture created earlier (camera renders to this texture)
> - Raw image added to the Canvas, texture set to the render texture created earlier (this raw image shows what the second camera has rendered)
> 
> You can tweak the second camera's orthographic size, the size of the raw image, and the resolution of the render texture.

**Comment by BlizzardBunny** [comment]
will reopen this when needed
