### ISSUE TITLE
RECOMMENDATION: Add more feedback to failure in Check-Up task

### ISSUE THREAD

**Issue by TheMagicalFishTaco** [BlizzardBunny/RAWRS#21]
put feedback in failure dialog ("animal is overstressed!") because some players are dumb

**Comment by BlizzardBunny** [comment]
added text instructions to the tasks. but this will also be more evident when I have arzen's sprites, as the sprite will change dynamically

**Comment by BlizzardBunny** [comment]
implement arzen sprites
